LEVEL := ../..
include $(LEVEL)/Makefile.common

all: TriangleCounting-opt3

TriangleCounting-opt3: TriangleCounting-opt3.cc
	$(MPICXX) $(CFLAGS) -O3 TriangleCounting-opt3.cc -o TriangleCounting-opt3
